server:
  port: 8087
  
spring:
  application:
    name: database
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/mydata
    username: root
    password: yu950905
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #mapper.xml
  type-aliases-package: com.spring.database.entity
  
#jdbc:mysql://192.168.0.132:3306/ns
#spring.datasource.url=jdbc:mysql://192.168.0.132:3306/lianwa?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username=root
#kxyx92108
#spring.datasource.password=kxyx92108
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#sixth database
#spring.redis.database=6  
#spring.redis.host=127.0.0.1
#spring.redis.port=6379
#spring.redis.password=
#spring.redis.timeout=500

#mybatis /Users/Jason/Desktop/DataBaseDemo/src/main
#mybatis.mapper-locations=classpath:mapper/*	.xml  #mapper.xml
#mybatis.type-aliases-package=com.spring.database.entity   #instance 
